on:
  pull_request:
    branches:
      - main
name: Coding style lint
jobs:
  php-cs-fixer:
    name: Run PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Run PHP-CS-Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix PHP coding style
